steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/paiva-lima-empreendimentos/paiva-lima/paiva-lima-api:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/paiva-lima-empreendimentos/paiva-lima/paiva-lima-api:latest']